# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 256f88b9ad44a85ca15caa9daf3802cfc3912fd2b1e9fbf54183d75a048250cfdbb5571fdcfeb6d199c2d01c7011d467fc5e0ed6f0761d75ae0a370296595797

test:
  secret_key_base: 9c3a4ba67adbfaee4e72f32cef308188372ce34fcb4c062c63c6a73a608652c8dd0b3fe3962e54d7fa430659ae30560391d05b084b2bf45cf59bfc6c8fdd8b56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
